config/routes.rb
Sasfeeds::Application.routes.draw do
  resources :asproducts

  resources :sasproducts

  resources :sasmaps

  resources :stuffs

end

app/models/sasproduct.rb
class Sasproduct < ActiveRecord::Base
  attr_accessible :AddToCartURL, :Bestseller, :Category, :Commission, :CompareTo, :CompatibleWith, :CrossSell, :Custom_1, :Custom_2, :Custom_3, :Custom_4, :Custom_5, :Description, :ISBN, :Manufacturer, :MerchantCategory, :MerchantGroup, :MerchantID, :MerchantSubCategory, :MerchantSubgroup, :Option1, :Option2, :Option3, :Option4, :Option5, :PartNumber, :QuantityDiscount, :ReservedForFutureUse1, :ReservedForFutureUse2, :ReservedForFutureUse3, :ReservedForFutureUse4, :ReservedForFutureUse5, :ReservedForFutureUse6, :ReservedForFutureUse7, :ReservedForFutureUse8, :ReservedForFutureUse9, :Retail_Price, :ReviewsRSSURL, :SKU, :SearchTerms, :ShortDescription, :Status, :StoreID, :Subcategory, :UPC, :URL_to_image, :URL_to_product, :URL_to_thumbnail_image, :name, :price
end

app/controllers/sasproducts_controller.rb
class SasproductsController < ApplicationController
  # GET /sasproducts
  # GET /sasproducts.json
  def index
    @sasproducts = Sasproduct.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sasproducts }
    end
  end

  # GET /sasproducts/1
  # GET /sasproducts/1.json
  def show
    @sasproduct = Sasproduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sasproduct }
    end
  end

  # GET /sasproducts/new
  # GET /sasproducts/new.json
  def new
    @sasproduct = Sasproduct.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sasproduct }
    end
  end

  # GET /sasproducts/1/edit
  def edit
    @sasproduct = Sasproduct.find(params[:id])
  end

  # POST /sasproducts
  # POST /sasproducts.json
  def create
    @sasproduct = Sasproduct.new(params[:sasproduct])

    respond_to do |format|
      if @sasproduct.save
        format.html { redirect_to @sasproduct, notice: 'Sasproduct was successfully created.' }
        format.json { render json: @sasproduct, status: :created, location: @sasproduct }
      else
        format.html { render action: "new" }
        format.json { render json: @sasproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sasproducts/1
  # PUT /sasproducts/1.json
  def update
    @sasproduct = Sasproduct.find(params[:id])

    respond_to do |format|
      if @sasproduct.update_attributes(params[:sasproduct])
        format.html { redirect_to @sasproduct, notice: 'Sasproduct was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sasproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sasproducts/1
  # DELETE /sasproducts/1.json
  def destroy
    @sasproduct = Sasproduct.find(params[:id])
    @sasproduct.destroy

    respond_to do |format|
      format.html { redirect_to sasproducts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sasproducts_helper.rb
module SasproductsHelper
end

app/views/sasproducts/_form.html.erb
<%= form_for(@sasproduct) do |f| %>
  <% if @sasproduct.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sasproduct.errors.count, "error") %> prohibited this sasproduct from being saved:</h2>

      <ul>
      <% @sasproduct.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :SKU %><br />
    <%= f.text_field :SKU %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :URL_to_product %><br />
    <%= f.text_field :URL_to_product %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :Retail_Price %><br />
    <%= f.text_field :Retail_Price %>
  </div>
  <div class="field">
    <%= f.label :URL_to_image %><br />
    <%= f.text_field :URL_to_image %>
  </div>
  <div class="field">
    <%= f.label :URL_to_thumbnail_image %><br />
    <%= f.text_field :URL_to_thumbnail_image %>
  </div>
  <div class="field">
    <%= f.label :Commission %><br />
    <%= f.text_field :Commission %>
  </div>
  <div class="field">
    <%= f.label :Category %><br />
    <%= f.text_field :Category %>
  </div>
  <div class="field">
    <%= f.label :Subcategory %><br />
    <%= f.text_field :Subcategory %>
  </div>
  <div class="field">
    <%= f.label :Description %><br />
    <%= f.text_area :Description %>
  </div>
  <div class="field">
    <%= f.label :SearchTerms %><br />
    <%= f.text_area :SearchTerms %>
  </div>
  <div class="field">
    <%= f.label :Status %><br />
    <%= f.text_field :Status %>
  </div>
  <div class="field">
    <%= f.label :MerchantID %><br />
    <%= f.text_field :MerchantID %>
  </div>
  <div class="field">
    <%= f.label :Custom_1 %><br />
    <%= f.text_field :Custom_1 %>
  </div>
  <div class="field">
    <%= f.label :Custom_2 %><br />
    <%= f.text_field :Custom_2 %>
  </div>
  <div class="field">
    <%= f.label :Custom_3 %><br />
    <%= f.text_field :Custom_3 %>
  </div>
  <div class="field">
    <%= f.label :Custom_4 %><br />
    <%= f.text_field :Custom_4 %>
  </div>
  <div class="field">
    <%= f.label :Custom_5 %><br />
    <%= f.text_field :Custom_5 %>
  </div>
  <div class="field">
    <%= f.label :StoreID %><br />
    <%= f.text_field :StoreID %>
  </div>
  <div class="field">
    <%= f.label :Manufacturer %><br />
    <%= f.text_field :Manufacturer %>
  </div>
  <div class="field">
    <%= f.label :PartNumber %><br />
    <%= f.text_field :PartNumber %>
  </div>
  <div class="field">
    <%= f.label :MerchantCategory %><br />
    <%= f.text_field :MerchantCategory %>
  </div>
  <div class="field">
    <%= f.label :MerchantSubCategory %><br />
    <%= f.text_field :MerchantSubCategory %>
  </div>
  <div class="field">
    <%= f.label :ShortDescription %><br />
    <%= f.text_field :ShortDescription %>
  </div>
  <div class="field">
    <%= f.label :ISBN %><br />
    <%= f.text_field :ISBN %>
  </div>
  <div class="field">
    <%= f.label :UPC %><br />
    <%= f.text_field :UPC %>
  </div>
  <div class="field">
    <%= f.label :CrossSell %><br />
    <%= f.text_field :CrossSell %>
  </div>
  <div class="field">
    <%= f.label :MerchantGroup %><br />
    <%= f.text_field :MerchantGroup %>
  </div>
  <div class="field">
    <%= f.label :MerchantSubgroup %><br />
    <%= f.text_field :MerchantSubgroup %>
  </div>
  <div class="field">
    <%= f.label :CompatibleWith %><br />
    <%= f.text_field :CompatibleWith %>
  </div>
  <div class="field">
    <%= f.label :CompareTo %><br />
    <%= f.text_field :CompareTo %>
  </div>
  <div class="field">
    <%= f.label :QuantityDiscount %><br />
    <%= f.text_field :QuantityDiscount %>
  </div>
  <div class="field">
    <%= f.label :Bestseller %><br />
    <%= f.text_field :Bestseller %>
  </div>
  <div class="field">
    <%= f.label :AddToCartURL %><br />
    <%= f.text_field :AddToCartURL %>
  </div>
  <div class="field">
    <%= f.label :ReviewsRSSURL %><br />
    <%= f.text_field :ReviewsRSSURL %>
  </div>
  <div class="field">
    <%= f.label :Option1 %><br />
    <%= f.text_field :Option1 %>
  </div>
  <div class="field">
    <%= f.label :Option2 %><br />
    <%= f.text_field :Option2 %>
  </div>
  <div class="field">
    <%= f.label :Option3 %><br />
    <%= f.text_field :Option3 %>
  </div>
  <div class="field">
    <%= f.label :Option4 %><br />
    <%= f.text_field :Option4 %>
  </div>
  <div class="field">
    <%= f.label :Option5 %><br />
    <%= f.text_field :Option5 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse1 %><br />
    <%= f.text_field :ReservedForFutureUse1 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse2 %><br />
    <%= f.text_field :ReservedForFutureUse2 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse3 %><br />
    <%= f.text_field :ReservedForFutureUse3 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse4 %><br />
    <%= f.text_field :ReservedForFutureUse4 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse5 %><br />
    <%= f.text_field :ReservedForFutureUse5 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse6 %><br />
    <%= f.text_field :ReservedForFutureUse6 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse7 %><br />
    <%= f.text_field :ReservedForFutureUse7 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse8 %><br />
    <%= f.text_field :ReservedForFutureUse8 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse9 %><br />
    <%= f.text_field :ReservedForFutureUse9 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sasproducts/edit.html.erb
<h1>Editing sasproduct</h1>

<%= render 'form' %>

<%= link_to 'Show', @sasproduct %> |
<%= link_to 'Back', sasproducts_path %>

app/views/sasproducts/index.html.erb
<h1>Listing sasproducts</h1>

<table>
  <tr>
    <th>Sku</th>
    <th>Name</th>
    <th>Url to product</th>
    <th>Price</th>
    <th>Retail price</th>
    <th>Url to image</th>
    <th>Url to thumbnail image</th>
    <th>Commission</th>
    <th>Category</th>
    <th>Subcategory</th>
    <th>Description</th>
    <th>Searchterms</th>
    <th>Status</th>
    <th>Merchantid</th>
    <th>Custom 1</th>
    <th>Custom 2</th>
    <th>Custom 3</th>
    <th>Custom 4</th>
    <th>Custom 5</th>
    <th>Storeid</th>
    <th>Manufacturer</th>
    <th>Partnumber</th>
    <th>Merchantcategory</th>
    <th>Merchantsubcategory</th>
    <th>Shortdescription</th>
    <th>Isbn</th>
    <th>Upc</th>
    <th>Crosssell</th>
    <th>Merchantgroup</th>
    <th>Merchantsubgroup</th>
    <th>Compatiblewith</th>
    <th>Compareto</th>
    <th>Quantitydiscount</th>
    <th>Bestseller</th>
    <th>Addtocarturl</th>
    <th>Reviewsrssurl</th>
    <th>Option1</th>
    <th>Option2</th>
    <th>Option3</th>
    <th>Option4</th>
    <th>Option5</th>
    <th>Reservedforfutureuse1</th>
    <th>Reservedforfutureuse2</th>
    <th>Reservedforfutureuse3</th>
    <th>Reservedforfutureuse4</th>
    <th>Reservedforfutureuse5</th>
    <th>Reservedforfutureuse6</th>
    <th>Reservedforfutureuse7</th>
    <th>Reservedforfutureuse8</th>
    <th>Reservedforfutureuse9</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sasproducts.each do |sasproduct| %>
  <tr>
    <td><%= sasproduct.SKU %></td>
    <td><%= sasproduct.name %></td>
    <td><%= sasproduct.URL_to_product %></td>
    <td><%= sasproduct.price %></td>
    <td><%= sasproduct.Retail_Price %></td>
    <td><%= sasproduct.URL_to_image %></td>
    <td><%= sasproduct.URL_to_thumbnail_image %></td>
    <td><%= sasproduct.Commission %></td>
    <td><%= sasproduct.Category %></td>
    <td><%= sasproduct.Subcategory %></td>
    <td><%= sasproduct.Description %></td>
    <td><%= sasproduct.SearchTerms %></td>
    <td><%= sasproduct.Status %></td>
    <td><%= sasproduct.MerchantID %></td>
    <td><%= sasproduct.Custom_1 %></td>
    <td><%= sasproduct.Custom_2 %></td>
    <td><%= sasproduct.Custom_3 %></td>
    <td><%= sasproduct.Custom_4 %></td>
    <td><%= sasproduct.Custom_5 %></td>
    <td><%= sasproduct.StoreID %></td>
    <td><%= sasproduct.Manufacturer %></td>
    <td><%= sasproduct.PartNumber %></td>
    <td><%= sasproduct.MerchantCategory %></td>
    <td><%= sasproduct.MerchantSubCategory %></td>
    <td><%= sasproduct.ShortDescription %></td>
    <td><%= sasproduct.ISBN %></td>
    <td><%= sasproduct.UPC %></td>
    <td><%= sasproduct.CrossSell %></td>
    <td><%= sasproduct.MerchantGroup %></td>
    <td><%= sasproduct.MerchantSubgroup %></td>
    <td><%= sasproduct.CompatibleWith %></td>
    <td><%= sasproduct.CompareTo %></td>
    <td><%= sasproduct.QuantityDiscount %></td>
    <td><%= sasproduct.Bestseller %></td>
    <td><%= sasproduct.AddToCartURL %></td>
    <td><%= sasproduct.ReviewsRSSURL %></td>
    <td><%= sasproduct.Option1 %></td>
    <td><%= sasproduct.Option2 %></td>
    <td><%= sasproduct.Option3 %></td>
    <td><%= sasproduct.Option4 %></td>
    <td><%= sasproduct.Option5 %></td>
    <td><%= sasproduct.ReservedForFutureUse1 %></td>
    <td><%= sasproduct.ReservedForFutureUse2 %></td>
    <td><%= sasproduct.ReservedForFutureUse3 %></td>
    <td><%= sasproduct.ReservedForFutureUse4 %></td>
    <td><%= sasproduct.ReservedForFutureUse5 %></td>
    <td><%= sasproduct.ReservedForFutureUse6 %></td>
    <td><%= sasproduct.ReservedForFutureUse7 %></td>
    <td><%= sasproduct.ReservedForFutureUse8 %></td>
    <td><%= sasproduct.ReservedForFutureUse9 %></td>
    <td><%= link_to 'Show', sasproduct %></td>
    <td><%= link_to 'Edit', edit_sasproduct_path(sasproduct) %></td>
    <td><%= link_to 'Destroy', sasproduct, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sasproduct', new_sasproduct_path %>

app/views/sasproducts/new.html.erb
<h1>New sasproduct</h1>

<%= render 'form' %>

<%= link_to 'Back', sasproducts_path %>

app/views/sasproducts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sku:</b>
  <%= @sasproduct.SKU %>
</p>

<p>
  <b>Name:</b>
  <%= @sasproduct.name %>
</p>

<p>
  <b>Url to product:</b>
  <%= @sasproduct.URL_to_product %>
</p>

<p>
  <b>Price:</b>
  <%= @sasproduct.price %>
</p>

<p>
  <b>Retail price:</b>
  <%= @sasproduct.Retail_Price %>
</p>

<p>
  <b>Url to image:</b>
  <%= @sasproduct.URL_to_image %>
</p>

<p>
  <b>Url to thumbnail image:</b>
  <%= @sasproduct.URL_to_thumbnail_image %>
</p>

<p>
  <b>Commission:</b>
  <%= @sasproduct.Commission %>
</p>

<p>
  <b>Category:</b>
  <%= @sasproduct.Category %>
</p>

<p>
  <b>Subcategory:</b>
  <%= @sasproduct.Subcategory %>
</p>

<p>
  <b>Description:</b>
  <%= @sasproduct.Description %>
</p>

<p>
  <b>Searchterms:</b>
  <%= @sasproduct.SearchTerms %>
</p>

<p>
  <b>Status:</b>
  <%= @sasproduct.Status %>
</p>

<p>
  <b>Merchantid:</b>
  <%= @sasproduct.MerchantID %>
</p>

<p>
  <b>Custom 1:</b>
  <%= @sasproduct.Custom_1 %>
</p>

<p>
  <b>Custom 2:</b>
  <%= @sasproduct.Custom_2 %>
</p>

<p>
  <b>Custom 3:</b>
  <%= @sasproduct.Custom_3 %>
</p>

<p>
  <b>Custom 4:</b>
  <%= @sasproduct.Custom_4 %>
</p>

<p>
  <b>Custom 5:</b>
  <%= @sasproduct.Custom_5 %>
</p>

<p>
  <b>Storeid:</b>
  <%= @sasproduct.StoreID %>
</p>

<p>
  <b>Manufacturer:</b>
  <%= @sasproduct.Manufacturer %>
</p>

<p>
  <b>Partnumber:</b>
  <%= @sasproduct.PartNumber %>
</p>

<p>
  <b>Merchantcategory:</b>
  <%= @sasproduct.MerchantCategory %>
</p>

<p>
  <b>Merchantsubcategory:</b>
  <%= @sasproduct.MerchantSubCategory %>
</p>

<p>
  <b>Shortdescription:</b>
  <%= @sasproduct.ShortDescription %>
</p>

<p>
  <b>Isbn:</b>
  <%= @sasproduct.ISBN %>
</p>

<p>
  <b>Upc:</b>
  <%= @sasproduct.UPC %>
</p>

<p>
  <b>Crosssell:</b>
  <%= @sasproduct.CrossSell %>
</p>

<p>
  <b>Merchantgroup:</b>
  <%= @sasproduct.MerchantGroup %>
</p>

<p>
  <b>Merchantsubgroup:</b>
  <%= @sasproduct.MerchantSubgroup %>
</p>

<p>
  <b>Compatiblewith:</b>
  <%= @sasproduct.CompatibleWith %>
</p>

<p>
  <b>Compareto:</b>
  <%= @sasproduct.CompareTo %>
</p>

<p>
  <b>Quantitydiscount:</b>
  <%= @sasproduct.QuantityDiscount %>
</p>

<p>
  <b>Bestseller:</b>
  <%= @sasproduct.Bestseller %>
</p>

<p>
  <b>Addtocarturl:</b>
  <%= @sasproduct.AddToCartURL %>
</p>

<p>
  <b>Reviewsrssurl:</b>
  <%= @sasproduct.ReviewsRSSURL %>
</p>

<p>
  <b>Option1:</b>
  <%= @sasproduct.Option1 %>
</p>

<p>
  <b>Option2:</b>
  <%= @sasproduct.Option2 %>
</p>

<p>
  <b>Option3:</b>
  <%= @sasproduct.Option3 %>
</p>

<p>
  <b>Option4:</b>
  <%= @sasproduct.Option4 %>
</p>

<p>
  <b>Option5:</b>
  <%= @sasproduct.Option5 %>
</p>

<p>
  <b>Reservedforfutureuse1:</b>
  <%= @sasproduct.ReservedForFutureUse1 %>
</p>

<p>
  <b>Reservedforfutureuse2:</b>
  <%= @sasproduct.ReservedForFutureUse2 %>
</p>

<p>
  <b>Reservedforfutureuse3:</b>
  <%= @sasproduct.ReservedForFutureUse3 %>
</p>

<p>
  <b>Reservedforfutureuse4:</b>
  <%= @sasproduct.ReservedForFutureUse4 %>
</p>

<p>
  <b>Reservedforfutureuse5:</b>
  <%= @sasproduct.ReservedForFutureUse5 %>
</p>

<p>
  <b>Reservedforfutureuse6:</b>
  <%= @sasproduct.ReservedForFutureUse6 %>
</p>

<p>
  <b>Reservedforfutureuse7:</b>
  <%= @sasproduct.ReservedForFutureUse7 %>
</p>

<p>
  <b>Reservedforfutureuse8:</b>
  <%= @sasproduct.ReservedForFutureUse8 %>
</p>

<p>
  <b>Reservedforfutureuse9:</b>
  <%= @sasproduct.ReservedForFutureUse9 %>
</p>


<%= link_to 'Edit', edit_sasproduct_path(@sasproduct) %> |
<%= link_to 'Back', sasproducts_path %>