config/routes.rb
Sasfeeds::Application.routes.draw do
  resources :asproducts

  resources :sasproducts

  resources :sasmaps

  resources :stuffs

end

app/models/asproduct.rb
class Asproduct < ActiveRecord::Base
  attr_accessible :accessgroup, :accessories, :backorder_message, :catalogid, :categories, :categoryspecial, :cost, :date_created, :depth, :description, :display_stock, :displaytext, :distributor, :eproduct_expire, :eproduct_instructions, :eproduct_password, :eproduct_path, :eproduct_random, :eproduct_reuseserial, :eproduct_serial, :extended_description, :extra_field_1, :extra_field_10, :extra_field_2, :extra_field_3, :extra_field_4, :extra_field_5, :extra_field_6, :extra_field_7, :extra_field_8, :extra_field_9, :filename, :fractional_qty, :free_shipping, :giftcertificate, :height, :hide, :hide_1, :hide_10, :hide_2, :hide_3, :hide_4, :hide_5, :hide_6, :hide_7, :hide_8, :hide_9, :homespecial, :image1, :image2, :image3, :image4, :imagecaption1, :imagecaption2, :imagecaption3, :imagecaption4, :instock_message, :keywords, :last_update, :listing_displaytype, :loginlevel, :manufacturer, :maximumorder, :metatags, :mfgid, :minimumorder, :minorderpkg, :name, :nonsearchable, :nontax, :notforsale, :onsale, :outofstock_message, :price, :price2, :price3, :price_1, :price_10, :price_2, :price_3, :price_4, :price_5, :price_6, :price_7, :price_8, :price_9, :pricing_groupopt, :qtydiscount_opt, :qtyoptions, :realmedia, :redirectto, :related, :reward_disable, :reward_points, :reward_redeem, :saleprice, :self_ship, :shipcost, :show_out_stock, :sku, :sorting, :stock, :stock_alert, :tax_code, :thumbnail, :title, :usecatoptions, :userid, :weight, :width
end

app/controllers/asproducts_controller.rb
class AsproductsController < ApplicationController
  # GET /asproducts
  # GET /asproducts.json
  def index
    @asproducts = Asproduct.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @asproducts }
    end
  end

  # GET /asproducts/1
  # GET /asproducts/1.json
  def show
    @asproduct = Asproduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asproduct }
    end
  end

  # GET /asproducts/new
  # GET /asproducts/new.json
  def new
    @asproduct = Asproduct.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asproduct }
    end
  end

  # GET /asproducts/1/edit
  def edit
    @asproduct = Asproduct.find(params[:id])
  end

  # POST /asproducts
  # POST /asproducts.json
  def create
    @asproduct = Asproduct.new(params[:asproduct])

    respond_to do |format|
      if @asproduct.save
        format.html { redirect_to @asproduct, notice: 'Asproduct was successfully created.' }
        format.json { render json: @asproduct, status: :created, location: @asproduct }
      else
        format.html { render action: "new" }
        format.json { render json: @asproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /asproducts/1
  # PUT /asproducts/1.json
  def update
    @asproduct = Asproduct.find(params[:id])

    respond_to do |format|
      if @asproduct.update_attributes(params[:asproduct])
        format.html { redirect_to @asproduct, notice: 'Asproduct was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asproducts/1
  # DELETE /asproducts/1.json
  def destroy
    @asproduct = Asproduct.find(params[:id])
    @asproduct.destroy

    respond_to do |format|
      format.html { redirect_to asproducts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/asproducts_helper.rb
module AsproductsHelper
end

app/views/asproducts/edit.html.erb
<h1>Editing asproduct</h1>

<%= render 'form' %>

<%= link_to 'Show', @asproduct %> |
<%= link_to 'Back', asproducts_path %>

app/views/asproducts/index.html.erb
<h1>Listing asproducts</h1>

<table>
  <tr>
    <th>Catalogid</th>
    <th>Sku</th>
    <th>Name</th>
    <th>Categories</th>
    <th>Mfgid</th>
    <th>Manufacturer</th>
    <th>Distributor</th>
    <th>Cost</th>
    <th>Price</th>
    <th>Price2</th>
    <th>Price3</th>
    <th>Saleprice</th>
    <th>Onsale</th>
    <th>Stock</th>
    <th>Stock alert</th>
    <th>Display stock</th>
    <th>Weight</th>
    <th>Minimumorder</th>
    <th>Maximumorder</th>
    <th>Date created</th>
    <th>Description</th>
    <th>Extended description</th>
    <th>Keywords</th>
    <th>Sorting</th>
    <th>Thumbnail</th>
    <th>Image1</th>
    <th>Image2</th>
    <th>Image3</th>
    <th>Image4</th>
    <th>Realmedia</th>
    <th>Related</th>
    <th>Accessories</th>
    <th>Shipcost</th>
    <th>Imagecaption1</th>
    <th>Imagecaption2</th>
    <th>Imagecaption3</th>
    <th>Imagecaption4</th>
    <th>Title</th>
    <th>Metatags</th>
    <th>Displaytext</th>
    <th>Eproduct password</th>
    <th>Eproduct random</th>
    <th>Eproduct expire</th>
    <th>Eproduct path</th>
    <th>Eproduct serial</th>
    <th>Eproduct instructions</th>
    <th>Homespecial</th>
    <th>Categoryspecial</th>
    <th>Hide</th>
    <th>Free shipping</th>
    <th>Nontax</th>
    <th>Notforsale</th>
    <th>Giftcertificate</th>
    <th>Userid</th>
    <th>Last update</th>
    <th>Extra field 1</th>
    <th>Extra field 2</th>
    <th>Extra field 3</th>
    <th>Extra field 4</th>
    <th>Extra field 5</th>
    <th>Extra field 6</th>
    <th>Extra field 7</th>
    <th>Extra field 8</th>
    <th>Extra field 9</th>
    <th>Extra field 10</th>
    <th>Usecatoptions</th>
    <th>Qtyoptions</th>
    <th>Price 1</th>
    <th>Price 2</th>
    <th>Price 3</th>
    <th>Price 4</th>
    <th>Price 5</th>
    <th>Price 6</th>
    <th>Price 7</th>
    <th>Price 8</th>
    <th>Price 9</th>
    <th>Price 10</th>
    <th>Hide 1</th>
    <th>Hide 2</th>
    <th>Hide 3</th>
    <th>Hide 4</th>
    <th>Hide 5</th>
    <th>Hide 6</th>
    <th>Hide 7</th>
    <th>Hide 8</th>
    <th>Hide 9</th>
    <th>Hide 10</th>
    <th>Minorderpkg</th>
    <th>Listing displaytype</th>
    <th>Show out stock</th>
    <th>Pricing groupopt</th>
    <th>Qtydiscount opt</th>
    <th>Loginlevel</th>
    <th>Redirectto</th>
    <th>Accessgroup</th>
    <th>Self ship</th>
    <th>Tax code</th>
    <th>Eproduct reuseserial</th>
    <th>Nonsearchable</th>
    <th>Instock message</th>
    <th>Outofstock message</th>
    <th>Backorder message</th>
    <th>Height</th>
    <th>Width</th>
    <th>Depth</th>
    <th>Reward points</th>
    <th>Reward disable</th>
    <th>Reward redeem</th>
    <th>Filename</th>
    <th>Fractional qty</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @asproducts.each do |asproduct| %>
  <tr>
    <td><%= asproduct.catalogid %></td>
    <td><%= asproduct.sku %></td>
    <td><%= asproduct.name %></td>
    <td><%= asproduct.categories %></td>
    <td><%= asproduct.mfgid %></td>
    <td><%= asproduct.manufacturer %></td>
    <td><%= asproduct.distributor %></td>
    <td><%= asproduct.cost %></td>
    <td><%= asproduct.price %></td>
    <td><%= asproduct.price2 %></td>
    <td><%= asproduct.price3 %></td>
    <td><%= asproduct.saleprice %></td>
    <td><%= asproduct.onsale %></td>
    <td><%= asproduct.stock %></td>
    <td><%= asproduct.stock_alert %></td>
    <td><%= asproduct.display_stock %></td>
    <td><%= asproduct.weight %></td>
    <td><%= asproduct.minimumorder %></td>
    <td><%= asproduct.maximumorder %></td>
    <td><%= asproduct.date_created %></td>
    <td><%= asproduct.description %></td>
    <td><%= asproduct.extended_description %></td>
    <td><%= asproduct.keywords %></td>
    <td><%= asproduct.sorting %></td>
    <td><%= asproduct.thumbnail %></td>
    <td><%= asproduct.image1 %></td>
    <td><%= asproduct.image2 %></td>
    <td><%= asproduct.image3 %></td>
    <td><%= asproduct.image4 %></td>
    <td><%= asproduct.realmedia %></td>
    <td><%= asproduct.related %></td>
    <td><%= asproduct.accessories %></td>
    <td><%= asproduct.shipcost %></td>
    <td><%= asproduct.imagecaption1 %></td>
    <td><%= asproduct.imagecaption2 %></td>
    <td><%= asproduct.imagecaption3 %></td>
    <td><%= asproduct.imagecaption4 %></td>
    <td><%= asproduct.title %></td>
    <td><%= asproduct.metatags %></td>
    <td><%= asproduct.displaytext %></td>
    <td><%= asproduct.eproduct_password %></td>
    <td><%= asproduct.eproduct_random %></td>
    <td><%= asproduct.eproduct_expire %></td>
    <td><%= asproduct.eproduct_path %></td>
    <td><%= asproduct.eproduct_serial %></td>
    <td><%= asproduct.eproduct_instructions %></td>
    <td><%= asproduct.homespecial %></td>
    <td><%= asproduct.categoryspecial %></td>
    <td><%= asproduct.hide %></td>
    <td><%= asproduct.free_shipping %></td>
    <td><%= asproduct.nontax %></td>
    <td><%= asproduct.notforsale %></td>
    <td><%= asproduct.giftcertificate %></td>
    <td><%= asproduct.userid %></td>
    <td><%= asproduct.last_update %></td>
    <td><%= asproduct.extra_field_1 %></td>
    <td><%= asproduct.extra_field_2 %></td>
    <td><%= asproduct.extra_field_3 %></td>
    <td><%= asproduct.extra_field_4 %></td>
    <td><%= asproduct.extra_field_5 %></td>
    <td><%= asproduct.extra_field_6 %></td>
    <td><%= asproduct.extra_field_7 %></td>
    <td><%= asproduct.extra_field_8 %></td>
    <td><%= asproduct.extra_field_9 %></td>
    <td><%= asproduct.extra_field_10 %></td>
    <td><%= asproduct.usecatoptions %></td>
    <td><%= asproduct.qtyoptions %></td>
    <td><%= asproduct.price_1 %></td>
    <td><%= asproduct.price_2 %></td>
    <td><%= asproduct.price_3 %></td>
    <td><%= asproduct.price_4 %></td>
    <td><%= asproduct.price_5 %></td>
    <td><%= asproduct.price_6 %></td>
    <td><%= asproduct.price_7 %></td>
    <td><%= asproduct.price_8 %></td>
    <td><%= asproduct.price_9 %></td>
    <td><%= asproduct.price_10 %></td>
    <td><%= asproduct.hide_1 %></td>
    <td><%= asproduct.hide_2 %></td>
    <td><%= asproduct.hide_3 %></td>
    <td><%= asproduct.hide_4 %></td>
    <td><%= asproduct.hide_5 %></td>
    <td><%= asproduct.hide_6 %></td>
    <td><%= asproduct.hide_7 %></td>
    <td><%= asproduct.hide_8 %></td>
    <td><%= asproduct.hide_9 %></td>
    <td><%= asproduct.hide_10 %></td>
    <td><%= asproduct.minorderpkg %></td>
    <td><%= asproduct.listing_displaytype %></td>
    <td><%= asproduct.show_out_stock %></td>
    <td><%= asproduct.pricing_groupopt %></td>
    <td><%= asproduct.qtydiscount_opt %></td>
    <td><%= asproduct.loginlevel %></td>
    <td><%= asproduct.redirectto %></td>
    <td><%= asproduct.accessgroup %></td>
    <td><%= asproduct.self_ship %></td>
    <td><%= asproduct.tax_code %></td>
    <td><%= asproduct.eproduct_reuseserial %></td>
    <td><%= asproduct.nonsearchable %></td>
    <td><%= asproduct.instock_message %></td>
    <td><%= asproduct.outofstock_message %></td>
    <td><%= asproduct.backorder_message %></td>
    <td><%= asproduct.height %></td>
    <td><%= asproduct.width %></td>
    <td><%= asproduct.depth %></td>
    <td><%= asproduct.reward_points %></td>
    <td><%= asproduct.reward_disable %></td>
    <td><%= asproduct.reward_redeem %></td>
    <td><%= asproduct.filename %></td>
    <td><%= asproduct.fractional_qty %></td>
    <td><%= link_to 'Show', asproduct %></td>
    <td><%= link_to 'Edit', edit_asproduct_path(asproduct) %></td>
    <td><%= link_to 'Destroy', asproduct, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Asproduct', new_asproduct_path %>

app/views/asproducts/new.html.erb
<h1>New asproduct</h1>

<%= render 'form' %>

<%= link_to 'Back', asproducts_path %>

app/views/asproducts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Catalogid:</b>
  <%= @asproduct.catalogid %>
</p>

<p>
  <b>Sku:</b>
  <%= @asproduct.sku %>
</p>

<p>
  <b>Name:</b>
  <%= @asproduct.name %>
</p>

<p>
  <b>Categories:</b>
  <%= @asproduct.categories %>
</p>

<p>
  <b>Mfgid:</b>
  <%= @asproduct.mfgid %>
</p>

<p>
  <b>Manufacturer:</b>
  <%= @asproduct.manufacturer %>
</p>

<p>
  <b>Distributor:</b>
  <%= @asproduct.distributor %>
</p>

<p>
  <b>Cost:</b>
  <%= @asproduct.cost %>
</p>

<p>
  <b>Price:</b>
  <%= @asproduct.price %>
</p>

<p>
  <b>Price2:</b>
  <%= @asproduct.price2 %>
</p>

<p>
  <b>Price3:</b>
  <%= @asproduct.price3 %>
</p>

<p>
  <b>Saleprice:</b>
  <%= @asproduct.saleprice %>
</p>

<p>
  <b>Onsale:</b>
  <%= @asproduct.onsale %>
</p>

<p>
  <b>Stock:</b>
  <%= @asproduct.stock %>
</p>

<p>
  <b>Stock alert:</b>
  <%= @asproduct.stock_alert %>
</p>

<p>
  <b>Display stock:</b>
  <%= @asproduct.display_stock %>
</p>

<p>
  <b>Weight:</b>
  <%= @asproduct.weight %>
</p>

<p>
  <b>Minimumorder:</b>
  <%= @asproduct.minimumorder %>
</p>

<p>
  <b>Maximumorder:</b>
  <%= @asproduct.maximumorder %>
</p>

<p>
  <b>Date created:</b>
  <%= @asproduct.date_created %>
</p>

<p>
  <b>Description:</b>
  <%= @asproduct.description %>
</p>

<p>
  <b>Extended description:</b>
  <%= @asproduct.extended_description %>
</p>

<p>
  <b>Keywords:</b>
  <%= @asproduct.keywords %>
</p>

<p>
  <b>Sorting:</b>
  <%= @asproduct.sorting %>
</p>

<p>
  <b>Thumbnail:</b>
  <%= @asproduct.thumbnail %>
</p>

<p>
  <b>Image1:</b>
  <%= @asproduct.image1 %>
</p>

<p>
  <b>Image2:</b>
  <%= @asproduct.image2 %>
</p>

<p>
  <b>Image3:</b>
  <%= @asproduct.image3 %>
</p>

<p>
  <b>Image4:</b>
  <%= @asproduct.image4 %>
</p>

<p>
  <b>Realmedia:</b>
  <%= @asproduct.realmedia %>
</p>

<p>
  <b>Related:</b>
  <%= @asproduct.related %>
</p>

<p>
  <b>Accessories:</b>
  <%= @asproduct.accessories %>
</p>

<p>
  <b>Shipcost:</b>
  <%= @asproduct.shipcost %>
</p>

<p>
  <b>Imagecaption1:</b>
  <%= @asproduct.imagecaption1 %>
</p>

<p>
  <b>Imagecaption2:</b>
  <%= @asproduct.imagecaption2 %>
</p>

<p>
  <b>Imagecaption3:</b>
  <%= @asproduct.imagecaption3 %>
</p>

<p>
  <b>Imagecaption4:</b>
  <%= @asproduct.imagecaption4 %>
</p>

<p>
  <b>Title:</b>
  <%= @asproduct.title %>
</p>

<p>
  <b>Metatags:</b>
  <%= @asproduct.metatags %>
</p>

<p>
  <b>Displaytext:</b>
  <%= @asproduct.displaytext %>
</p>

<p>
  <b>Eproduct password:</b>
  <%= @asproduct.eproduct_password %>
</p>

<p>
  <b>Eproduct random:</b>
  <%= @asproduct.eproduct_random %>
</p>

<p>
  <b>Eproduct expire:</b>
  <%= @asproduct.eproduct_expire %>
</p>

<p>
  <b>Eproduct path:</b>
  <%= @asproduct.eproduct_path %>
</p>

<p>
  <b>Eproduct serial:</b>
  <%= @asproduct.eproduct_serial %>
</p>

<p>
  <b>Eproduct instructions:</b>
  <%= @asproduct.eproduct_instructions %>
</p>

<p>
  <b>Homespecial:</b>
  <%= @asproduct.homespecial %>
</p>

<p>
  <b>Categoryspecial:</b>
  <%= @asproduct.categoryspecial %>
</p>

<p>
  <b>Hide:</b>
  <%= @asproduct.hide %>
</p>

<p>
  <b>Free shipping:</b>
  <%= @asproduct.free_shipping %>
</p>

<p>
  <b>Nontax:</b>
  <%= @asproduct.nontax %>
</p>

<p>
  <b>Notforsale:</b>
  <%= @asproduct.notforsale %>
</p>

<p>
  <b>Giftcertificate:</b>
  <%= @asproduct.giftcertificate %>
</p>

<p>
  <b>Userid:</b>
  <%= @asproduct.userid %>
</p>

<p>
  <b>Last update:</b>
  <%= @asproduct.last_update %>
</p>

<p>
  <b>Extra field 1:</b>
  <%= @asproduct.extra_field_1 %>
</p>

<p>
  <b>Extra field 2:</b>
  <%= @asproduct.extra_field_2 %>
</p>

<p>
  <b>Extra field 3:</b>
  <%= @asproduct.extra_field_3 %>
</p>

<p>
  <b>Extra field 4:</b>
  <%= @asproduct.extra_field_4 %>
</p>

<p>
  <b>Extra field 5:</b>
  <%= @asproduct.extra_field_5 %>
</p>

<p>
  <b>Extra field 6:</b>
  <%= @asproduct.extra_field_6 %>
</p>

<p>
  <b>Extra field 7:</b>
  <%= @asproduct.extra_field_7 %>
</p>

<p>
  <b>Extra field 8:</b>
  <%= @asproduct.extra_field_8 %>
</p>

<p>
  <b>Extra field 9:</b>
  <%= @asproduct.extra_field_9 %>
</p>

<p>
  <b>Extra field 10:</b>
  <%= @asproduct.extra_field_10 %>
</p>

<p>
  <b>Usecatoptions:</b>
  <%= @asproduct.usecatoptions %>
</p>

<p>
  <b>Qtyoptions:</b>
  <%= @asproduct.qtyoptions %>
</p>

<p>
  <b>Price 1:</b>
  <%= @asproduct.price_1 %>
</p>

<p>
  <b>Price 2:</b>
  <%= @asproduct.price_2 %>
</p>

<p>
  <b>Price 3:</b>
  <%= @asproduct.price_3 %>
</p>

<p>
  <b>Price 4:</b>
  <%= @asproduct.price_4 %>
</p>

<p>
  <b>Price 5:</b>
  <%= @asproduct.price_5 %>
</p>

<p>
  <b>Price 6:</b>
  <%= @asproduct.price_6 %>
</p>

<p>
  <b>Price 7:</b>
  <%= @asproduct.price_7 %>
</p>

<p>
  <b>Price 8:</b>
  <%= @asproduct.price_8 %>
</p>

<p>
  <b>Price 9:</b>
  <%= @asproduct.price_9 %>
</p>

<p>
  <b>Price 10:</b>
  <%= @asproduct.price_10 %>
</p>

<p>
  <b>Hide 1:</b>
  <%= @asproduct.hide_1 %>
</p>

<p>
  <b>Hide 2:</b>
  <%= @asproduct.hide_2 %>
</p>

<p>
  <b>Hide 3:</b>
  <%= @asproduct.hide_3 %>
</p>

<p>
  <b>Hide 4:</b>
  <%= @asproduct.hide_4 %>
</p>

<p>
  <b>Hide 5:</b>
  <%= @asproduct.hide_5 %>
</p>

<p>
  <b>Hide 6:</b>
  <%= @asproduct.hide_6 %>
</p>

<p>
  <b>Hide 7:</b>
  <%= @asproduct.hide_7 %>
</p>

<p>
  <b>Hide 8:</b>
  <%= @asproduct.hide_8 %>
</p>

<p>
  <b>Hide 9:</b>
  <%= @asproduct.hide_9 %>
</p>

<p>
  <b>Hide 10:</b>
  <%= @asproduct.hide_10 %>
</p>

<p>
  <b>Minorderpkg:</b>
  <%= @asproduct.minorderpkg %>
</p>

<p>
  <b>Listing displaytype:</b>
  <%= @asproduct.listing_displaytype %>
</p>

<p>
  <b>Show out stock:</b>
  <%= @asproduct.show_out_stock %>
</p>

<p>
  <b>Pricing groupopt:</b>
  <%= @asproduct.pricing_groupopt %>
</p>

<p>
  <b>Qtydiscount opt:</b>
  <%= @asproduct.qtydiscount_opt %>
</p>

<p>
  <b>Loginlevel:</b>
  <%= @asproduct.loginlevel %>
</p>

<p>
  <b>Redirectto:</b>
  <%= @asproduct.redirectto %>
</p>

<p>
  <b>Accessgroup:</b>
  <%= @asproduct.accessgroup %>
</p>

<p>
  <b>Self ship:</b>
  <%= @asproduct.self_ship %>
</p>

<p>
  <b>Tax code:</b>
  <%= @asproduct.tax_code %>
</p>

<p>
  <b>Eproduct reuseserial:</b>
  <%= @asproduct.eproduct_reuseserial %>
</p>

<p>
  <b>Nonsearchable:</b>
  <%= @asproduct.nonsearchable %>
</p>

<p>
  <b>Instock message:</b>
  <%= @asproduct.instock_message %>
</p>

<p>
  <b>Outofstock message:</b>
  <%= @asproduct.outofstock_message %>
</p>

<p>
  <b>Backorder message:</b>
  <%= @asproduct.backorder_message %>
</p>

<p>
  <b>Height:</b>
  <%= @asproduct.height %>
</p>

<p>
  <b>Width:</b>
  <%= @asproduct.width %>
</p>

<p>
  <b>Depth:</b>
  <%= @asproduct.depth %>
</p>

<p>
  <b>Reward points:</b>
  <%= @asproduct.reward_points %>
</p>

<p>
  <b>Reward disable:</b>
  <%= @asproduct.reward_disable %>
</p>

<p>
  <b>Reward redeem:</b>
  <%= @asproduct.reward_redeem %>
</p>

<p>
  <b>Filename:</b>
  <%= @asproduct.filename %>
</p>

<p>
  <b>Fractional qty:</b>
  <%= @asproduct.fractional_qty %>
</p>


<%= link_to 'Edit', edit_asproduct_path(@asproduct) %> |
<%= link_to 'Back', asproducts_path %>