config/routes.rb
Sasfeeds::Application.routes.draw do
  resources :asproducts

  resources :sasproducts

  resources :sasmaps

  resources :stuffs

end

app/models/sasmap.rb
class Sasmap < ActiveRecord::Base
  attr_accessible :AddToCartURL, :Bestseller, :Category, :Commission, :CompareTo, :CompatibleWith, :CrossSell, :Custom_1, :Custom_2, :Custom_3, :Custom_4, :Custom_5, :Description, :ISBN, :Manufacturer, :MerchantCategory, :MerchantGroup, :MerchantID, :MerchantSubCategory, :MerchantSubgroup, :Option1, :Option2, :Option3, :Option4, :Option5, :PartNumber, :QuantityDiscount, :ReservedForFutureUse1, :ReservedForFutureUse2, :ReservedForFutureUse3, :ReservedForFutureUse4, :ReservedForFutureUse5, :ReservedForFutureUse6, :ReservedForFutureUse7, :ReservedForFutureUse8, :ReservedForFutureUse9, :Retail_Price, :ReviewsRSSURL, :SKU, :SearchTerms, :ShortDescription, :Status, :StoreID, :Subcategory, :UPC, :URL_to_image, :URL_to_product, :URL_to_thumbnail_image, :name, :price
end

app/controllers/sasmaps_controller.rb
class SasmapsController < ApplicationController
  # GET /sasmaps
  # GET /sasmaps.json
  def index
    @sasmaps = Sasmap.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sasmaps }
    end
  end

  # GET /sasmaps/1
  # GET /sasmaps/1.json
  def show
    @sasmap = Sasmap.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sasmap }
    end
  end

  # GET /sasmaps/new
  # GET /sasmaps/new.json
  def new
    @sasmap = Sasmap.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sasmap }
    end
  end

  # GET /sasmaps/1/edit
  def edit
    @sasmap = Sasmap.find(params[:id])
  end

  # POST /sasmaps
  # POST /sasmaps.json
  def create
    @sasmap = Sasmap.new(params[:sasmap])

    respond_to do |format|
      if @sasmap.save
        format.html { redirect_to @sasmap, notice: 'Sasmap was successfully created.' }
        format.json { render json: @sasmap, status: :created, location: @sasmap }
      else
        format.html { render action: "new" }
        format.json { render json: @sasmap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sasmaps/1
  # PUT /sasmaps/1.json
  def update
    @sasmap = Sasmap.find(params[:id])

    respond_to do |format|
      if @sasmap.update_attributes(params[:sasmap])
        format.html { redirect_to @sasmap, notice: 'Sasmap was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sasmap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sasmaps/1
  # DELETE /sasmaps/1.json
  def destroy
    @sasmap = Sasmap.find(params[:id])
    @sasmap.destroy

    respond_to do |format|
      format.html { redirect_to sasmaps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sasmaps_helper.rb
module SasmapsHelper
end

app/views/sasmaps/_form.html.erb
<%= form_for(@sasmap) do |f| %>
  <% if @sasmap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sasmap.errors.count, "error") %> prohibited this sasmap from being saved:</h2>

      <ul>
      <% @sasmap.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :SKU %><br />
    <%= f.text_field :SKU %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :URL_to_product %><br />
    <%= f.text_field :URL_to_product %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :Retail_Price %><br />
    <%= f.text_field :Retail_Price %>
  </div>
  <div class="field">
    <%= f.label :URL_to_image %><br />
    <%= f.text_field :URL_to_image %>
  </div>
  <div class="field">
    <%= f.label :URL_to_thumbnail_image %><br />
    <%= f.text_field :URL_to_thumbnail_image %>
  </div>
  <div class="field">
    <%= f.label :Commission %><br />
    <%= f.text_field :Commission %>
  </div>
  <div class="field">
    <%= f.label :Category %><br />
    <%= f.text_field :Category %>
  </div>
  <div class="field">
    <%= f.label :Subcategory %><br />
    <%= f.text_field :Subcategory %>
  </div>
  <div class="field">
    <%= f.label :Description %><br />
    <%= f.text_area :Description %>
  </div>
  <div class="field">
    <%= f.label :SearchTerms %><br />
    <%= f.text_area :SearchTerms %>
  </div>
  <div class="field">
    <%= f.label :Status %><br />
    <%= f.text_field :Status %>
  </div>
  <div class="field">
    <%= f.label :MerchantID %><br />
    <%= f.text_field :MerchantID %>
  </div>
  <div class="field">
    <%= f.label :Custom_1 %><br />
    <%= f.text_field :Custom_1 %>
  </div>
  <div class="field">
    <%= f.label :Custom_2 %><br />
    <%= f.text_field :Custom_2 %>
  </div>
  <div class="field">
    <%= f.label :Custom_3 %><br />
    <%= f.text_field :Custom_3 %>
  </div>
  <div class="field">
    <%= f.label :Custom_4 %><br />
    <%= f.text_field :Custom_4 %>
  </div>
  <div class="field">
    <%= f.label :Custom_5 %><br />
    <%= f.text_field :Custom_5 %>
  </div>
  <div class="field">
    <%= f.label :StoreID %><br />
    <%= f.text_field :StoreID %>
  </div>
  <div class="field">
    <%= f.label :Manufacturer %><br />
    <%= f.text_field :Manufacturer %>
  </div>
  <div class="field">
    <%= f.label :PartNumber %><br />
    <%= f.text_field :PartNumber %>
  </div>
  <div class="field">
    <%= f.label :MerchantCategory %><br />
    <%= f.text_field :MerchantCategory %>
  </div>
  <div class="field">
    <%= f.label :MerchantSubCategory %><br />
    <%= f.text_field :MerchantSubCategory %>
  </div>
  <div class="field">
    <%= f.label :ShortDescription %><br />
    <%= f.text_field :ShortDescription %>
  </div>
  <div class="field">
    <%= f.label :ISBN %><br />
    <%= f.text_field :ISBN %>
  </div>
  <div class="field">
    <%= f.label :UPC %><br />
    <%= f.text_field :UPC %>
  </div>
  <div class="field">
    <%= f.label :CrossSell %><br />
    <%= f.text_field :CrossSell %>
  </div>
  <div class="field">
    <%= f.label :MerchantGroup %><br />
    <%= f.text_field :MerchantGroup %>
  </div>
  <div class="field">
    <%= f.label :MerchantSubgroup %><br />
    <%= f.text_field :MerchantSubgroup %>
  </div>
  <div class="field">
    <%= f.label :CompatibleWith %><br />
    <%= f.text_field :CompatibleWith %>
  </div>
  <div class="field">
    <%= f.label :CompareTo %><br />
    <%= f.text_field :CompareTo %>
  </div>
  <div class="field">
    <%= f.label :QuantityDiscount %><br />
    <%= f.text_field :QuantityDiscount %>
  </div>
  <div class="field">
    <%= f.label :Bestseller %><br />
    <%= f.text_field :Bestseller %>
  </div>
  <div class="field">
    <%= f.label :AddToCartURL %><br />
    <%= f.text_field :AddToCartURL %>
  </div>
  <div class="field">
    <%= f.label :ReviewsRSSURL %><br />
    <%= f.text_field :ReviewsRSSURL %>
  </div>
  <div class="field">
    <%= f.label :Option1 %><br />
    <%= f.text_field :Option1 %>
  </div>
  <div class="field">
    <%= f.label :Option2 %><br />
    <%= f.text_field :Option2 %>
  </div>
  <div class="field">
    <%= f.label :Option3 %><br />
    <%= f.text_field :Option3 %>
  </div>
  <div class="field">
    <%= f.label :Option4 %><br />
    <%= f.text_field :Option4 %>
  </div>
  <div class="field">
    <%= f.label :Option5 %><br />
    <%= f.text_field :Option5 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse1 %><br />
    <%= f.text_field :ReservedForFutureUse1 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse2 %><br />
    <%= f.text_field :ReservedForFutureUse2 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse3 %><br />
    <%= f.text_field :ReservedForFutureUse3 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse4 %><br />
    <%= f.text_field :ReservedForFutureUse4 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse5 %><br />
    <%= f.text_field :ReservedForFutureUse5 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse6 %><br />
    <%= f.text_field :ReservedForFutureUse6 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse7 %><br />
    <%= f.text_field :ReservedForFutureUse7 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse8 %><br />
    <%= f.text_field :ReservedForFutureUse8 %>
  </div>
  <div class="field">
    <%= f.label :ReservedForFutureUse9 %><br />
    <%= f.text_field :ReservedForFutureUse9 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sasmaps/edit.html.erb
<h1>Editing sasmap</h1>

<%= render 'form' %>

<%= link_to 'Show', @sasmap %> |
<%= link_to 'Back', sasmaps_path %>

app/views/sasmaps/index.html.erb
<h1>Listing sasmaps</h1>

<table>
  <tr>
    <th>Sku</th>
    <th>Name</th>
    <th>Url to product</th>
    <th>Price</th>
    <th>Retail price</th>
    <th>Url to image</th>
    <th>Url to thumbnail image</th>
    <th>Commission</th>
    <th>Category</th>
    <th>Subcategory</th>
    <th>Description</th>
    <th>Searchterms</th>
    <th>Status</th>
    <th>Merchantid</th>
    <th>Custom 1</th>
    <th>Custom 2</th>
    <th>Custom 3</th>
    <th>Custom 4</th>
    <th>Custom 5</th>
    <th>Storeid</th>
    <th>Manufacturer</th>
    <th>Partnumber</th>
    <th>Merchantcategory</th>
    <th>Merchantsubcategory</th>
    <th>Shortdescription</th>
    <th>Isbn</th>
    <th>Upc</th>
    <th>Crosssell</th>
    <th>Merchantgroup</th>
    <th>Merchantsubgroup</th>
    <th>Compatiblewith</th>
    <th>Compareto</th>
    <th>Quantitydiscount</th>
    <th>Bestseller</th>
    <th>Addtocarturl</th>
    <th>Reviewsrssurl</th>
    <th>Option1</th>
    <th>Option2</th>
    <th>Option3</th>
    <th>Option4</th>
    <th>Option5</th>
    <th>Reservedforfutureuse1</th>
    <th>Reservedforfutureuse2</th>
    <th>Reservedforfutureuse3</th>
    <th>Reservedforfutureuse4</th>
    <th>Reservedforfutureuse5</th>
    <th>Reservedforfutureuse6</th>
    <th>Reservedforfutureuse7</th>
    <th>Reservedforfutureuse8</th>
    <th>Reservedforfutureuse9</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sasmaps.each do |sasmap| %>
  <tr>
    <td><%= sasmap.SKU %></td>
    <td><%= sasmap.name %></td>
    <td><%= sasmap.URL_to_product %></td>
    <td><%= sasmap.price %></td>
    <td><%= sasmap.Retail_Price %></td>
    <td><%= sasmap.URL_to_image %></td>
    <td><%= sasmap.URL_to_thumbnail_image %></td>
    <td><%= sasmap.Commission %></td>
    <td><%= sasmap.Category %></td>
    <td><%= sasmap.Subcategory %></td>
    <td><%= sasmap.Description %></td>
    <td><%= sasmap.SearchTerms %></td>
    <td><%= sasmap.Status %></td>
    <td><%= sasmap.MerchantID %></td>
    <td><%= sasmap.Custom_1 %></td>
    <td><%= sasmap.Custom_2 %></td>
    <td><%= sasmap.Custom_3 %></td>
    <td><%= sasmap.Custom_4 %></td>
    <td><%= sasmap.Custom_5 %></td>
    <td><%= sasmap.StoreID %></td>
    <td><%= sasmap.Manufacturer %></td>
    <td><%= sasmap.PartNumber %></td>
    <td><%= sasmap.MerchantCategory %></td>
    <td><%= sasmap.MerchantSubCategory %></td>
    <td><%= sasmap.ShortDescription %></td>
    <td><%= sasmap.ISBN %></td>
    <td><%= sasmap.UPC %></td>
    <td><%= sasmap.CrossSell %></td>
    <td><%= sasmap.MerchantGroup %></td>
    <td><%= sasmap.MerchantSubgroup %></td>
    <td><%= sasmap.CompatibleWith %></td>
    <td><%= sasmap.CompareTo %></td>
    <td><%= sasmap.QuantityDiscount %></td>
    <td><%= sasmap.Bestseller %></td>
    <td><%= sasmap.AddToCartURL %></td>
    <td><%= sasmap.ReviewsRSSURL %></td>
    <td><%= sasmap.Option1 %></td>
    <td><%= sasmap.Option2 %></td>
    <td><%= sasmap.Option3 %></td>
    <td><%= sasmap.Option4 %></td>
    <td><%= sasmap.Option5 %></td>
    <td><%= sasmap.ReservedForFutureUse1 %></td>
    <td><%= sasmap.ReservedForFutureUse2 %></td>
    <td><%= sasmap.ReservedForFutureUse3 %></td>
    <td><%= sasmap.ReservedForFutureUse4 %></td>
    <td><%= sasmap.ReservedForFutureUse5 %></td>
    <td><%= sasmap.ReservedForFutureUse6 %></td>
    <td><%= sasmap.ReservedForFutureUse7 %></td>
    <td><%= sasmap.ReservedForFutureUse8 %></td>
    <td><%= sasmap.ReservedForFutureUse9 %></td>
    <td><%= link_to 'Show', sasmap %></td>
    <td><%= link_to 'Edit', edit_sasmap_path(sasmap) %></td>
    <td><%= link_to 'Destroy', sasmap, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sasmap', new_sasmap_path %>

app/views/sasmaps/new.html.erb
<h1>New sasmap</h1>

<%= render 'form' %>

<%= link_to 'Back', sasmaps_path %>

app/views/sasmaps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sku:</b>
  <%= @sasmap.SKU %>
</p>

<p>
  <b>Name:</b>
  <%= @sasmap.name %>
</p>

<p>
  <b>Url to product:</b>
  <%= @sasmap.URL_to_product %>
</p>

<p>
  <b>Price:</b>
  <%= @sasmap.price %>
</p>

<p>
  <b>Retail price:</b>
  <%= @sasmap.Retail_Price %>
</p>

<p>
  <b>Url to image:</b>
  <%= @sasmap.URL_to_image %>
</p>

<p>
  <b>Url to thumbnail image:</b>
  <%= @sasmap.URL_to_thumbnail_image %>
</p>

<p>
  <b>Commission:</b>
  <%= @sasmap.Commission %>
</p>

<p>
  <b>Category:</b>
  <%= @sasmap.Category %>
</p>

<p>
  <b>Subcategory:</b>
  <%= @sasmap.Subcategory %>
</p>

<p>
  <b>Description:</b>
  <%= @sasmap.Description %>
</p>

<p>
  <b>Searchterms:</b>
  <%= @sasmap.SearchTerms %>
</p>

<p>
  <b>Status:</b>
  <%= @sasmap.Status %>
</p>

<p>
  <b>Merchantid:</b>
  <%= @sasmap.MerchantID %>
</p>

<p>
  <b>Custom 1:</b>
  <%= @sasmap.Custom_1 %>
</p>

<p>
  <b>Custom 2:</b>
  <%= @sasmap.Custom_2 %>
</p>

<p>
  <b>Custom 3:</b>
  <%= @sasmap.Custom_3 %>
</p>

<p>
  <b>Custom 4:</b>
  <%= @sasmap.Custom_4 %>
</p>

<p>
  <b>Custom 5:</b>
  <%= @sasmap.Custom_5 %>
</p>

<p>
  <b>Storeid:</b>
  <%= @sasmap.StoreID %>
</p>

<p>
  <b>Manufacturer:</b>
  <%= @sasmap.Manufacturer %>
</p>

<p>
  <b>Partnumber:</b>
  <%= @sasmap.PartNumber %>
</p>

<p>
  <b>Merchantcategory:</b>
  <%= @sasmap.MerchantCategory %>
</p>

<p>
  <b>Merchantsubcategory:</b>
  <%= @sasmap.MerchantSubCategory %>
</p>

<p>
  <b>Shortdescription:</b>
  <%= @sasmap.ShortDescription %>
</p>

<p>
  <b>Isbn:</b>
  <%= @sasmap.ISBN %>
</p>

<p>
  <b>Upc:</b>
  <%= @sasmap.UPC %>
</p>

<p>
  <b>Crosssell:</b>
  <%= @sasmap.CrossSell %>
</p>

<p>
  <b>Merchantgroup:</b>
  <%= @sasmap.MerchantGroup %>
</p>

<p>
  <b>Merchantsubgroup:</b>
  <%= @sasmap.MerchantSubgroup %>
</p>

<p>
  <b>Compatiblewith:</b>
  <%= @sasmap.CompatibleWith %>
</p>

<p>
  <b>Compareto:</b>
  <%= @sasmap.CompareTo %>
</p>

<p>
  <b>Quantitydiscount:</b>
  <%= @sasmap.QuantityDiscount %>
</p>

<p>
  <b>Bestseller:</b>
  <%= @sasmap.Bestseller %>
</p>

<p>
  <b>Addtocarturl:</b>
  <%= @sasmap.AddToCartURL %>
</p>

<p>
  <b>Reviewsrssurl:</b>
  <%= @sasmap.ReviewsRSSURL %>
</p>

<p>
  <b>Option1:</b>
  <%= @sasmap.Option1 %>
</p>

<p>
  <b>Option2:</b>
  <%= @sasmap.Option2 %>
</p>

<p>
  <b>Option3:</b>
  <%= @sasmap.Option3 %>
</p>

<p>
  <b>Option4:</b>
  <%= @sasmap.Option4 %>
</p>

<p>
  <b>Option5:</b>
  <%= @sasmap.Option5 %>
</p>

<p>
  <b>Reservedforfutureuse1:</b>
  <%= @sasmap.ReservedForFutureUse1 %>
</p>

<p>
  <b>Reservedforfutureuse2:</b>
  <%= @sasmap.ReservedForFutureUse2 %>
</p>

<p>
  <b>Reservedforfutureuse3:</b>
  <%= @sasmap.ReservedForFutureUse3 %>
</p>

<p>
  <b>Reservedforfutureuse4:</b>
  <%= @sasmap.ReservedForFutureUse4 %>
</p>

<p>
  <b>Reservedforfutureuse5:</b>
  <%= @sasmap.ReservedForFutureUse5 %>
</p>

<p>
  <b>Reservedforfutureuse6:</b>
  <%= @sasmap.ReservedForFutureUse6 %>
</p>

<p>
  <b>Reservedforfutureuse7:</b>
  <%= @sasmap.ReservedForFutureUse7 %>
</p>

<p>
  <b>Reservedforfutureuse8:</b>
  <%= @sasmap.ReservedForFutureUse8 %>
</p>

<p>
  <b>Reservedforfutureuse9:</b>
  <%= @sasmap.ReservedForFutureUse9 %>
</p>


<%= link_to 'Edit', edit_sasmap_path(@sasmap) %> |
<%= link_to 'Back', sasmaps_path %>